# Generated by Django 3.2.19 on 2023-05-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='address',
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='type',
            field=models.IntegerField(choices=[(1, 'Motorcycle'), (2, 'Car'), (3, 'Van')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.IntegerField(choices=[(1, 'Motorcycle'), (2, 'Car'), (3, 'Van')]),
        ),
    ]
